server:
  session-timeout: 18000
  ssl:
    enabled: false
  #    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8888
#    uri-encoding: utf-8
#security:
#  basic:
#    enabled: false
spring:
  data:
    elasticsearch:
      cluster-name: node-1
      cluster-nodes: 192.168.98.128:9200
      repositories:
        enabled: true
  resources:
    static-locations: classpath:/resources/,classpath:/templates/,classpath:/static/,classpath:/public/
    #在静态文件路径后增加Md5字符串，字符串的值根据文件内容自动生成，所以在文件内容改变时自动改变。
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
      enabled: true
  devtools:
    restart:
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  redis:
    host: 192.168.98.128
    port: 6379
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  rabbitmq:
    host: 192.168.98.128
    port: 5672
    username: myMq
    password: abc123xxx.
    virtual-host: /admin
mybatis:
  configuration:
    #自动将数据库带下划线的表字段值映射到Java类的驼峰字段上
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
#分页插件
pagehelper:
  helper-dialect: mysql
  #为 true时，当前页大于总页数时，会返回最后一页，为false时，有数据就返回，无数据则为空
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


#图片上传目标路径
web:
  upload-path: D:/code/novel/novel-admin/src/main/resources/static/images
