package cn.lsr.noveladmin.mapping;

import cn.lsr.noveladmin.model.Graphtimecount;
import cn.lsr.noveladmin.model.GraphtimecountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraphtimecountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    long countByExample(GraphtimecountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    int deleteByExample(GraphtimecountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    int insert(Graphtimecount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    int insertSelective(Graphtimecount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    List<Graphtimecount> selectByExample(GraphtimecountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    Graphtimecount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") Graphtimecount record, @Param("example") GraphtimecountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    int updateByExample(@Param("record") Graphtimecount record, @Param("example") GraphtimecountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    int updateByPrimaryKeySelective(Graphtimecount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphtimecount
     *
     * @mbg.generated Mon Oct 25 22:35:48 CST 2021
     */
    int updateByPrimaryKey(Graphtimecount record);
}