package cn.lsr.noveladmin.mapping;

import cn.lsr.noveladmin.model.TagBookExample;
import cn.lsr.noveladmin.model.TagBookKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag-book
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    long countByExample(TagBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag-book
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    int deleteByExample(TagBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag-book
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    int deleteByPrimaryKey(TagBookKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag-book
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    int insert(TagBookKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag-book
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    int insertSelective(TagBookKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag-book
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    List<TagBookKey> selectByExample(TagBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag-book
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    int updateByExampleSelective(@Param("record") TagBookKey record, @Param("example") TagBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag-book
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    int updateByExample(@Param("record") TagBookKey record, @Param("example") TagBookExample example);
}