package cn.lsr.noveladmin.mapping;

import cn.lsr.noveladmin.model.TypeBookExample;
import cn.lsr.noveladmin.model.TypeBookKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TypeBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type-book
     *
     * @mbg.generated Fri Nov 05 11:46:01 CST 2021
     */
    long countByExample(TypeBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type-book
     *
     * @mbg.generated Fri Nov 05 11:46:01 CST 2021
     */
    int deleteByExample(TypeBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type-book
     *
     * @mbg.generated Fri Nov 05 11:46:01 CST 2021
     */
    int deleteByPrimaryKey(TypeBookKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type-book
     *
     * @mbg.generated Fri Nov 05 11:46:01 CST 2021
     */
    int insert(TypeBookKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type-book
     *
     * @mbg.generated Fri Nov 05 11:46:01 CST 2021
     */
    int insertSelective(TypeBookKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type-book
     *
     * @mbg.generated Fri Nov 05 11:46:01 CST 2021
     */
    List<TypeBookKey> selectByExample(TypeBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type-book
     *
     * @mbg.generated Fri Nov 05 11:46:01 CST 2021
     */
    int updateByExampleSelective(@Param("record") TypeBookKey record, @Param("example") TypeBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type-book
     *
     * @mbg.generated Fri Nov 05 11:46:01 CST 2021
     */
    int updateByExample(@Param("record") TypeBookKey record, @Param("example") TypeBookExample example);
}