package cn.lsr.noveladmin.model;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotEmpty;
import java.util.Date;
import java.util.Set;

@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Administrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.id
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.admin_name
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    @NotEmpty(message = "管理名不能为空")
    @Length(max = 36, message = "管理名最大长度为36")
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.admin_password
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    @NotEmpty(message = "管理密码不能为空")
    @Length(max = 36,message = "管理密码不能多于36位")
    private String adminPassword;

    /**
     * 角色集合
     */
    private Set<Role> roles;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.create_time
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    private Date createTime;

    public Set<Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.id
     *
     * @return the value of administrator.id
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */


    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.id
     *
     * @param id the value for administrator.id
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.admin_name
     *
     * @return the value of administrator.admin_name
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.admin_name
     *
     * @param adminName the value for administrator.admin_name
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.admin_password
     *
     * @return the value of administrator.admin_password
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.admin_password
     *
     * @param adminPassword the value for administrator.admin_password
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.create_time
     *
     * @return the value of administrator.create_time
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.create_time
     *
     * @param createTime the value for administrator.create_time
     *
     * @mbg.generated Sat Nov 06 21:24:30 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
