package cn.lsr.noveladmin.model;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import java.io.Serializable;
import java.util.Date;

public class Author implements Serializable {

    private static final long serialVersionUID = 5238056119874298959L;
    private Long id;

    @NotEmpty(message = "笔名不能为空")
    @Length(max = 36, message = "笔名最大长度为36")
    private String penName;

    @NotEmpty(message = "手机号不能为空")
    private String telPhone;

    private String chatAccount;

    @NotEmpty(message = "邮箱不能为空")
    @Email(message = "邮箱格式不正确")
    private String email;

    private Byte workDirection;

    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.id
     *
     * @return the value of author.id
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.id
     *
     * @param id the value for author.id
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.pen_name
     *
     * @return the value of author.pen_name
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public String getPenName() {
        return penName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.pen_name
     *
     * @param penName the value for author.pen_name
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public void setPenName(String penName) {
        this.penName = penName == null ? null : penName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.tel_phone
     *
     * @return the value of author.tel_phone
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.tel_phone
     *
     * @param telPhone the value for author.tel_phone
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone == null ? null : telPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.chat_account
     *
     * @return the value of author.chat_account
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public String getChatAccount() {
        return chatAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.chat_account
     *
     * @param chatAccount the value for author.chat_account
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public void setChatAccount(String chatAccount) {
        this.chatAccount = chatAccount == null ? null : chatAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.email
     *
     * @return the value of author.email
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.email
     *
     * @param email the value for author.email
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.work_direction
     *
     * @return the value of author.work_direction
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public Byte getWorkDirection() {
        return workDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.work_direction
     *
     * @param workDirection the value for author.work_direction
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public void setWorkDirection(Byte workDirection) {
        this.workDirection = workDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.create_time
     *
     * @return the value of author.create_time
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.create_time
     *
     * @param createTime the value for author.create_time
     *
     * @mbg.generated Sat Oct 23 22:04:51 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
