package cn.lsr.noveladmin.model;

import javafx.beans.DefaultProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.Length;
import org.springframework.beans.factory.annotation.Autowired;

import javax.validation.constraints.NotEmpty;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.work_direction
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Boolean workDirection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pic_url
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    @NotEmpty(message = "小说名不能为空")
    @Length(max = 50, message = "当前填写的小说名超过了50个字符")
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author_id
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Long authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author_name
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    @NotEmpty(message = "作者名不能为空")
    @Length(max = 50, message = "当前填写的作者名超过了50个字符")
    private String authorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_desc
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    @NotEmpty(message = "小说描述不能为空")
    @Length(max = 2000, message = "当前填写的小说描述超过了2000个字符")
    private String bookDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.score
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Float score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_status
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Boolean bookStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.visit_count
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Long visitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.word_count
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Integer wordCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.comment_count
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.last_index_update_time
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Date lastIndexUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.is_vip
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Boolean isVip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.status
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.create_time
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.is_recommend
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private Boolean isRecommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.type_name
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.work_direction
     *
     * @return the value of book.work_direction
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Boolean getWorkDirection() {
        return workDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.work_direction
     *
     * @param workDirection the value for book.work_direction
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setWorkDirection(Boolean workDirection) {
        this.workDirection = workDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.pic_url
     *
     * @return the value of book.pic_url
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.pic_url
     *
     * @param picUrl the value for book.pic_url
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author_id
     *
     * @return the value of book.author_id
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author_id
     *
     * @param authorId the value for book.author_id
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author_name
     *
     * @return the value of book.author_name
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author_name
     *
     * @param authorName the value for book.author_name
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_desc
     *
     * @return the value of book.book_desc
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public String getBookDesc() {
        return bookDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_desc
     *
     * @param bookDesc the value for book.book_desc
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setBookDesc(String bookDesc) {
        this.bookDesc = bookDesc == null ? null : bookDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.score
     *
     * @return the value of book.score
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.score
     *
     * @param score the value for book.score
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_status
     *
     * @return the value of book.book_status
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Boolean getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_status
     *
     * @param bookStatus the value for book.book_status
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setBookStatus(Boolean bookStatus) {
        this.bookStatus = bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.visit_count
     *
     * @return the value of book.visit_count
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Long getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.visit_count
     *
     * @param visitCount the value for book.visit_count
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setVisitCount(Long visitCount) {
        this.visitCount = visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.word_count
     *
     * @return the value of book.word_count
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Integer getWordCount() {
        return wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.word_count
     *
     * @param wordCount the value for book.word_count
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setWordCount(Integer wordCount) {
        this.wordCount = wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.comment_count
     *
     * @return the value of book.comment_count
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.comment_count
     *
     * @param commentCount the value for book.comment_count
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.last_index_update_time
     *
     * @return the value of book.last_index_update_time
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Date getLastIndexUpdateTime() {
        return lastIndexUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.last_index_update_time
     *
     * @param lastIndexUpdateTime the value for book.last_index_update_time
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setLastIndexUpdateTime(Date lastIndexUpdateTime) {
        this.lastIndexUpdateTime = lastIndexUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.is_vip
     *
     * @return the value of book.is_vip
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Boolean getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.is_vip
     *
     * @param isVip the value for book.is_vip
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setIsVip(Boolean isVip) {
        this.isVip = isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.status
     *
     * @return the value of book.status
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.status
     *
     * @param status the value for book.status
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.create_time
     *
     * @return the value of book.create_time
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.create_time
     *
     * @param createTime the value for book.create_time
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.is_recommend
     *
     * @return the value of book.is_recommend
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public Boolean getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.is_recommend
     *
     * @param isRecommend the value for book.is_recommend
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setIsRecommend(Boolean isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.type_name
     *
     * @return the value of book.type_name
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.type_name
     *
     * @param typeName the value for book.type_name
     *
     * @mbg.generated Fri Dec 03 11:17:13 CST 2021
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}
