package cn.lsr.noveladmin.model;

public class TagBookKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag-book.tag_id
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag-book.book_id
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    private Long bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag-book.tag_id
     *
     * @return the value of tag-book.tag_id
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag-book.tag_id
     *
     * @param tagId the value for tag-book.tag_id
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag-book.book_id
     *
     * @return the value of tag-book.book_id
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag-book.book_id
     *
     * @param bookId the value for tag-book.book_id
     *
     * @mbg.generated Fri Nov 05 11:45:29 CST 2021
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }
}