package cn.lsr.noveladmin.model;

import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotEmpty;
import java.util.Date;

public class Type {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.id
     *
     * @mbg.generated Fri Nov 05 11:46:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_name
     *
     * @mbg.generated Fri Nov 05 11:46:18 CST 2021
     */
    @NotEmpty(message = "类型名不能为空")
    @Length(max = 36, message = "类型名最大长度为36")
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.create_time
     *
     * @mbg.generated Fri Nov 05 11:46:18 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.id
     *
     * @return the value of type.id
     *
     * @mbg.generated Fri Nov 05 11:46:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.id
     *
     * @param id the value for type.id
     *
     * @mbg.generated Fri Nov 05 11:46:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_name
     *
     * @return the value of type.type_name
     *
     * @mbg.generated Fri Nov 05 11:46:18 CST 2021
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_name
     *
     * @param typeName the value for type.type_name
     *
     * @mbg.generated Fri Nov 05 11:46:18 CST 2021
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.create_time
     *
     * @return the value of type.create_time
     *
     * @mbg.generated Fri Nov 05 11:46:18 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.create_time
     *
     * @param createTime the value for type.create_time
     *
     * @mbg.generated Fri Nov 05 11:46:18 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
