package cn.lsr.noveladmin.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.Email;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotEmpty;
import java.util.Date;

@AllArgsConstructor
@NoArgsConstructor
@ToString
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    @NotEmpty(message = "用户名不能为空")
    @Length(max = 36, message = "用户名最大长度为36")
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    @NotEmpty(message = "用户密码不能为空")
    @Length(max = 36,message = "用户密码不能多于36位")
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tel_phone
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    @NotEmpty(message = "手机号不能为空")
    private String telPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pic_url
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.chat_account
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    private String chatAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    @NotEmpty(message = "邮箱不能为空")
    @Email(message = "邮箱格式不正确")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    private Byte userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.followed_count
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    private Long followedCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tel_phone
     *
     * @return the value of user.tel_phone
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tel_phone
     *
     * @param telPhone the value for user.tel_phone
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone == null ? null : telPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pic_url
     *
     * @return the value of user.pic_url
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pic_url
     *
     * @param picUrl the value for user.pic_url
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.chat_account
     *
     * @return the value of user.chat_account
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public String getChatAccount() {
        return chatAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.chat_account
     *
     * @param chatAccount the value for user.chat_account
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setChatAccount(String chatAccount) {
        this.chatAccount = chatAccount == null ? null : chatAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.followed_count
     *
     * @return the value of user.followed_count
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public Long getFollowedCount() {
        return followedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.followed_count
     *
     * @param followedCount the value for user.followed_count
     *
     * @mbg.generated Tue Nov 09 17:06:25 CST 2021
     */
    public void setFollowedCount(Long followedCount) {
        this.followedCount = followedCount;
    }
}
